### ISSUE TITLE
Did you ever try....

### ISSUE THREAD

**Issue by magoerlich** [Harry-Hopkinson/vs-code-runner#22]
...to press F5 in vanilla VSCode?

What's the benefit of this extension to the vanilla feature?

**Comment by Harry-Hopkinson** [comment]
Easy to use: vs-code-runner adds a "Run Code" button to the top of the editor window, making it easy to run code without having to remember keyboard shortcuts or navigate through menus, making it easier for beginners.

Multiple languages: vs-code-runner supports a wide range of programming languages, so you can use it regardless of the language you are working with. The same button appears no matter what project one is working with.

Output in console: vs-code-runner displays the output of your code in the console, making it easy to see the results of your code and any error messages that may have occurred.

Customisation: vs-code-runner allows you to customise the way your code is run, such as specifying additional command-line arguments or environment variables.

Integration with build systems: vs-code-runner can be integrated with build systems such as Make and CMake allowing you to build and run your code from within the editor.

**Comment by magoerlich** [comment]
VS Code has all these features built-in.

> Easy to use: vs-code-runner adds a "Run Code" button to the top of the editor window, making it easy to run code without having to remember keyboard shortcuts or navigate through menus, making it easier for beginners.

https://i.imgur.com/jPaRarj.png


> Multiple languages: vs-code-runner supports a wide range of programming languages, so you can use it regardless of the language you are working with. The same button appears no matter what project one is working with.

Vanilla VSCode runs every language your system is able to run....

> Output in console: vs-code-runner displays the output of your code in the console, making it easy to see the results of your code and any error messages that may have occurred.

Output is printed to the built-in Terminal

> Customisation: vs-code-runner allows you to customise the way your code is run, such as specifying additional command-line arguments or environment variables.

Ever heard of launch.json?

> Integration with build systems: vs-code-runner can be integrated with build systems such as Make and CMake allowing you to build and run your code from within the editor.

....launch.json????

My question was, what makes this extension better than using the vanilla features.

But i just took a closer look at the code, so nvm.
Maybe add a note to the README to make clear that this is a learning project for you.
Might help clarify things for people like me.

**Comment by Harry-Hopkinson** [comment]
I think it is clear, just take the time to read the README of a project before creating an issue
